web-server/iot/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'iot'

urlpatterns = [
    path('iot', login_required(views.IndexView.as_view()), name = 'index'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name = 'iot/login.html'), name = 'login'),
    path('iot/reload', login_required(views.reload), name = 'reload'),
    path('iot/switch', login_required(views.switch), name = 'switch')
]

web-server/server/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('iot.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()

web-server/iot/models.py
from django.db import models

# Create your models here.

web-server/iot/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic

#from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute

from datetime import datetime, timedelta

from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, NumberAttribute, UTCDateTimeAttribute

import json
import boto3

# Create your views here.

class IndexView(generic.TemplateView):
    template_name = "iot/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_data = Iot.queryChart(1)
        context['iot_data_temperature'] = all_data["iot_data_temperature"]
        context['iot_data_humidity'] = all_data["iot_data_humidity"]
        context['iot_data_pressure'] = all_data["iot_data_pressure"]
        context['iot_data_illumination'] = all_data["iot_data_illumination"]
        return context

def reload(request):
    data = request.POST.get("name-show-time-select")
    all_data = Iot.queryChart(int(data))
    return HttpResponse(json.dumps(all_data))

def switch(request):
    data = request.POST.get("type")
    now = datetime.now()
    iot = boto3.client('iot-data', region_name = 'ap-northeast-1')
    topic = 'pi/switch/op'
    payload = {
        "type": data,
        "timestamp": "{0:%Y-%m-%d %H:%M:%S}".format(now)
    }
    iot.publish(
        topic = topic,
        qos = 0,
        payload = json.dumps(payload, ensure_ascii=False)
    )

    return  HttpResponse('スイッチ操作({})が送信されました。({})'.format(data, now))

class Iot(Model):

    class Meta:
        table_name = "pi_info"
        region = 'ap-northeast-1'

    client_id = UnicodeAttribute(hash_key=True)
    timestamp = NumberAttribute(range_key=True)
    humidity = NumberAttribute()
    pressure = NumberAttribute()
    temperature = NumberAttribute()
    illumination = NumberAttribute()

    @staticmethod
    def queryChart(hours):
        now = datetime.now()
        time_1h = now - timedelta(hours = hours)
        time_1h_ts13 = int(time_1h.timestamp() * 1000)
        iot_data_temperature = []
        iot_data_humidity = []
        iot_data_pressure = []
        iot_data_illumination =[]
        for item in Iot.query('raspberrypi', Iot.timestamp > time_1h_ts13):
            x_time = datetime.fromtimestamp(
                item.timestamp / 1000).strftime("%Y/%m/%d %H:%M:%S")
            y_temperature = item.temperature
            y_humidity = item.humidity
            y_pressure = item.pressure
            y_illumination = item.illumination
            iot_data_temperature.append({"x": x_time, "y": y_temperature})
            iot_data_humidity.append({"x": x_time, "y": y_humidity})
            iot_data_pressure.append({"x": x_time, "y": y_pressure})
            iot_data_illumination.append({"x": x_time, "y": y_illumination})
        all_data = {
                "iot_data_temperature" : iot_data_temperature,
                "iot_data_humidity" : iot_data_humidity, 
                "iot_data_pressure" : iot_data_pressure,
                "iot_data_illumination" : iot_data_illumination
            }
        return all_data

web-server/iot/templates/iot/base.html
{% load static %}

<!doctype html>
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'iot/css/bootstrap.min.css' %}">

    <title>IoT ダッシュボード</title>
</head>

<body>
    <main role="main" class="container">
        <nav class="navbar navbar-light bg-light">
            <span class="navbar-brand mb-0 h1">IoT管理画面</span>
        </nav>
        {% block content %}{% endblock %}
    </main>
    <!-- Optional JavaScript -->
    <script src="{% static 'iot/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'iot/js/bootstrap.bundle.min.js' %}"></script>
    {% block script %}{% endblock %}
</body>

</html>

web-server/iot/templates/iot/index.html
{% extends "iot/base.html" %}
{% load static %}

{% block content %}

<div class="row">
  <div class="col">
    <form name="time-form" id="time-form" action="{% url 'iot:reload' %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="show-time">表示時間(X時間前)</label>
        <select class="form-control" id="id-show-time-select" name="name-show-time-select" >
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>12</option>
          <option>24</option>
        </select>
      </div>
      <button type="submit" class="btn btn-secondary mb-2">更新</button>
    </div>
  </form>
</div>
<div class="row">
  <div class="col-md">
    <canvas class="my-4 w-100" id="tempChart" width="900" height="380"></canvas>
  </div>
  <div class="col-md">
    <canvas class="my-4 w-100" id="humidChart" width="900" height="380"></canvas>
  </div>
</div>
<div class="row">
  <div class="col-md">
    <canvas class="my-4 w-100" id="prsChart" width="900" height="380"></canvas>
  </div>
  <div class="col-md">
    <canvas class="my-4 w-100" id="illChart" width="900" height="380"></canvas>
  </div>
</div>
<div class="row">
  <div class="col-md">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">エアコン電源ボタン</h5>
        <p class="card-text">電源のボタン操作</p>
        <div class="btn-group" role="group" aria-label="Basic example">
          <button type="button" id="button-switch-aircond" class="btn btn-secondary">ON/OFF</button>
        </div>
      </div>
      <div class="card-body" id="result-aircond"></div>
    </div>
  </div>
  <div class="col-md">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">照明電源ボタン</h5>
        <p class="card-text">電源のボタン操作</p>
        <div class="btn-group" role="group" aria-label="Basic example">
          <button type="button" id="button-switch-light" class="btn btn-secondary">ON/OFF</button>
        </div>
      </div>
      <div class="card-body" id="result-light"></div>
    </div> 
  </div>
</div>
{% endblock %}
<!-- Optional JavaScript -->
{% block script %}
<script src="{% static 'iot/js/js.cookie-2.2.1.min.js' %}"></script>
<script src="{% static 'iot/js/Chart.bundle.min.js' %}"></script>
{{ iot_data_temperature|json_script:"iot_data_temperature" }}
{{ iot_data_humidity|json_script:"iot_data_humidity" }}
{{ iot_data_pressure|json_script:"iot_data_pressure"}}
{{ iot_data_illumination|json_script:"iot_data_illumination"}}
<script>
  function setChart(chart_data, min, max, label) {
    var chart_data = {
      type: 'line',
      data: {
        datasets: [{
          label: label,
          data: chart_data,
        }]
      },
      options: {
        scales: {
          xAxes: [{
            type: 'time',
            distribution: 'linear',
            time: {
              displayFormats: {
                minute: 'HH:mm',
                hour: 'HH'
              }
            }
          }],
          yAxes: [{
            ticks: {
              beginAtZero: true,
              min: min,
              max: max
            }
          }]
        }
      }
    };
    return chart_data;
  }
  var tempJson = JSON.parse(document.getElementById('iot_data_temperature').textContent);
  var humidJson = JSON.parse(document.getElementById('iot_data_humidity').textContent);
  var prsJson = JSON.parse(document.getElementById('iot_data_pressure').textContent);
  var illJson = JSON.parse(document.getElementById('iot_data_illumination').textContent);
  var tempCtx = document.getElementById('tempChart').getContext('2d');
  var humidCtx = document.getElementById('humidChart').getContext('2d');
  var prsCtx = document.getElementById('prsChart').getContext('2d');
  var illCtx = document.getElementById('illChart').getContext('2d');
  if (tempChart) {
    tempChart.destroy()
  }
  if (humidChart)  {
    humidChart.destroy()
  }
  if (prsChart) {
    prsChart.destroy()
  }
  if (illChart) {
    illChart.destroy()
  }
  var tempChart = new Chart(tempCtx, setChart(tempJson, -5, 40, '温度'));
  var humidChart = new Chart(humidCtx, setChart(humidJson, 0, 100, '湿度'));
  var prsChart =  new Chart(prsCtx, setChart(prsJson, 1000, 1030, '気圧'));
  var illChart = new Chart(illCtx, setChart(illJson, 0, 100, '照度'));
  $("#time-form").submit( function(event) {
    event.preventDefault();
    var form = $(this);
  $.ajax({
    url: form.prop("action"),
    method: form.prop("method"),
    data: form.serialize(),
    timeout: 10000,
    dataType: "text",
  })
  .done( function(data) {
    var json = JSON.parse(data);
    if (tempChart) {
      tempChart.destroy()
    }
    if (humidChart)  {
      humidChart.destroy()
    }
    if (prsChart) {
      prsChart.destroy()
    }
    if (illChart) {
      illChart.destroy()
    }
    tempChart = new Chart(tempCtx, setChart(json.iot_data_temperature, -5, 40, '温度'));
    humidChart = new Chart(humidCtx, setChart(json.iot_data_humidity, 0, 100, '湿度'));
    prsChart =  new Chart(prsCtx, setChart(json.iot_data_pressure, 1000, 1030, '気圧'));
    illChart = new Chart(illCtx, setChart(json.iot_data_illumination, 0, 100, '照度'));
    })
  });
  function csrfSafeMethod(method) {
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  function switchOp(event){
    $(event.data.id).text('通信中...');
    var csrftoken = Cookies.get('csrftoken');
    $.ajax({
        url: "{% url 'iot:switch' %}",
        method: "POST",
        data: {
          "type": event.data.thing,
        },
        timeout: 5000,
        beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
        }
    })
    .done(function(data) {
        $(event.data.id).text('処理成功：' + data);
    })
    .fail(function() {
        $(event.data.id).text('処理失敗.');
    });
  }
  $('#button-switch-aircond').on('click', {id: '#result-aircond', thing: 'aircond'}, switchOp);
  $('#button-switch-light').on('click', {id: '#result-light', thing: 'light'}, switchOp);
</script>
{% endblock %}

web-server/iot/templates/iot/login.html
{% extends "iot/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

<form method="post" action="{% url 'iot:login' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-dark">ログイン</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}